### ISSUE TITLE
TypeError: ArLocal is not a constructor

### ISSUE THREAD

**Issue by luckyr13** [textury/arlocal#140]
Hello guys! Today I tried to run ArLocal 1.1.58 from node using the provided code example:

```js
import ArLocal from 'arlocal';

(async () => {
  const arLocal = new ArLocal();

  // Start is a Promise, we need to start it inside an async function.
  await arLocal.start();

  // Your tests here...

  // After we are done with our tests, let's close the connection.
  await arLocal.stop();
})();
```

But I'm getting this error:
```
/index.js:4
  const arLocal = new ArLocal();
                           ^

TypeError: ArLocal is not a constructor
    at file:///C:/xampp/htdocs/ardbweb/index.js:4:19
    at file:///C:/xampp/htdocs/ardbweb/index.js:13:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

What do you think that could be the problem? Am I doing something wrong? Thanks in advance!

**Comment by kouraf** [comment]
Hello, in order to use arlocal with js you can do this
```js
import ArLocal from "arlocal";
(async () => {
  const arLocal = new ArLocal.default();

  // Start is a Promise, we need to start it inside an async function.
  await arLocal.start();

  // Your tests here...

  // After we are done with our tests, let's close the connection.
  await arLocal.stop();
})();
```

**Comment by luckyr13** [comment]
> Hello, in order to use arlocal with js you can do this
> 
> ```js
> import ArLocal from "arlocal";
> (async () => {
>   const arLocal = new ArLocal.default();
> 
>   // Start is a Promise, we need to start it inside an async function.
>   await arLocal.start();
> 
>   // Your tests here...
> 
>   // After we are done with our tests, let's close the connection.
>   await arLocal.stop();
> })();
> ```

Thank you my friend! I'll give it a try 🤝
