### ISSUE TITLE
Unable to fetch data for transaction

### ISSUE THREAD

**Issue by kespinola** [textury/arlocal#5]
I've been having mixed success with retrieving transaction data. Normally the first transaction I execute completes and I'm able to fetch the blob but on the next transactions succeed but I get a 500 when querying the data.

This is a snippet of the logs.
```
  <-- GET /CK5KQH7jhAstXUs1RTzbtBUYG__UnqE0yvJXYdEMEng
[7/6/2021, 9:59:56 PM] {
  id: 'CK5KQH7jhAstXUs1RTzbtBUYG__UnqE0yvJXYdEMEng',
  owner: '-uNN6D6K4cDPW1liclKyUbuO3sGPd4saaqsLOzID2ZKj_Bnj4XN3bLG2qbKAEMj8fOAzfd_x68gKqZ78mR04YPZeKTJA7q_vYm5f3W3uV2fsNdWYZAGLODKy-npBiyG2Cnc1_TgkHic2fY-t4KeiZPp9AUGeS7B-rceXacZfo-cR5bgFOTmPIM4G8s83kT-QiCQg71l8H4R-OY3NFNfIqNwOQ9NLNUjbcvBsySbUmHd3nrZ-eVaCke0YnGfq5C4AK1XuA-kDsW9b6JfA7guTtPabTdWQtgw8-mJsDzw-XZVn13UBNrz-1CDM2wpW0GVEw1gNvwIxfymAY7oZplhRGzNnKwqSEGz3bHpyGQWn4yuF52oSHiklX7hiiBp2lcblFnHRZC-knsZ4B0MCyWXywNNCXQJcid_AEZX1sDp9A6jHJ7_ERTMZitAq8lSAk2wINlv6Q9KEveU3Oucm0iRMwCfJVCWEMGjw-x7cDDEuaEcS4yvjnhQNGbk7UGcJPiagTxbh-hNAYiR_MNTpZUG5HbYnJ-OIcX7-ZFaJ3YK_YcifqFmg-q23ts4XaVH6c-q_sdkCH8TGzkGQWE2d8WlgekjnoP060QHdoq0EeaONpHagsIKdXWqRkyz2yW8iLLuRDFO1Zoi8spOLIeLoPEcDuxQAjxdL_-WEb2dw_PF6T5c',
  tags: [
    { name: 'Q29udGVudC1UeXBl', value: 'dGV4dC9jc3M' },
    { name: 'aG9sYXBsZXg6c3ViZG9tYWlu', value: 'ZXNwaQ' },
    {
      name: 'c29sYW5hOnB1YmtleQ',
      value: 'MlVuc2pjWHlYVEpHTEdjVXdCWVNUeEpWd0M5S1lmYU5ibWQ0d0trNHpDb1A'
    },
    { name: 'U2lnbmluZy1DbGllbnQ', value: 'QXJDb25uZWN0' },
    { name: 'U2lnbmluZy1DbGllbnQtVmVyc2lvbg', value: 'MC4zLjA' }
  ],
  target: '',
  quantity: '0',
  reward: '1159427880',
  signature: 'RaGUq7NiHwwsG_QkkI11HjUWv_gCA_8y1Bxwbwrcg3VwYF6SGGG2menxM_WFKwuNzUUUxCHvr3M-xIbBVxfXk5nQEXvMzRHS46WLDkvdTJzYzM181KoMrBcTOC46ojJDUocGZ_Z8jsnKcqkcRlIJf8t-w7xzWPD1YDrAJVGg_9BDhsapgAlCP4W0jG9vRGNKPt3h5boyAiqTKJyV0smpPYUiYvyjVAZLIO5imbv8ihpyA6x7fT8FbcdLBf6TjJbXbzst9otHQnixAuuVaQC1B53F2vqQ41oGif0hzedF3Dqu78_5Y2NAJnnV_kdiM4qE6Q8moPqEOskTQmXUneh8hslkdgo3GQaLQOZ5f55UItZoRSwJMD57k14s8UwUdUvpnVCGFmpmF0B5OYT6PWVIfoMCjHyMlYY0NUHs_IaeyBEketYUtiYsUWoo-mcXngG9j_UhfU5CK-YCqvC-QfOaB6e3CGF2r-0n0M-JIDZQOZNDC1X0vLVZEQegzmvu7b3czjCA0nrpWD4qSuzvkziT35NBdFNCwOeNMtvivxI6nlw8Xe_2v4NKTV2Nayu2QOJXLmfgyT5wliqhOuKDgdmuA0ak632mZ-2MaAjb-_DTKsMHiI4O3DaIFYADlzVKKR34KmfJtz_PBVw3GlQq_PjQcn7JWyTAGMS8K7lApjcHjRY',
  last_tx: 'jcYh7SdtqSmRUcauAxDMLFpLHzbyaw5JNmoOj9JVbec',
  data_size: 590,
  content_type: 'text/css',
  format: 2,
  height: 0,
  owner_address: 'xxxxx',
  data_root: 'IWVseuzIvOYniH6WWhvHeoYy7kKEkZSKsXY6_ahw_bnEb0IPlzPLmRSZnew-tDpMJVQGgzqErCXO844JQdvmXc',
  parent: null,
  created_at: '2021-07-07 04:50:21'
}
  xxx GET /CK5KQH7jhAstXUs1RTzbtBUYG__UnqE0yvJXYdEMEng 500 3ms -

  TypeError: Cannot read property 'data' of null
      at /home/espi/.npm/_npx/93eb0fdaba426b32/node_modules/@textury/arlocal/bin/routes/data.js:65:66
      at Generator.next (<anonymous>)
      at fulfilled (/home/espi/.npm/_npx/93eb0fdaba426b32/node_modules/@textury/arlocal/bin/routes/data.js:5:58)  
```

**Comment by kespinola** [comment]
This happens with the second transaction I submit. The transaction is accepted but when I request the contents at `http://localhost:1984/{tx} the server response with 500.`Cant read property data of null.

**Comment by kespinola** [comment]
The txs.db has both entries with txtid set to the transaction id queryable by the server.

**Comment by kespinola** [comment]
I have a fork and receive the below error when running `yarn dev`

```
11:18:32 AM - Starting compilation in watch mode...

src/app.ts(23,16): error TS2664: Invalid module name in augmentation, module 'Koa' cannot be found.
src/routes/data.ts(16,29): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/data.ts(19,43): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/data.ts(19,55): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/data.ts(26,7): error TS2339: Property 'logging' does not exist on type 'RouterContext<any, {}>'.
src/routes/data.ts(35,29): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/data.ts(38,43): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/data.ts(38,55): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/data.ts(45,7): error TS2339: Property 'logging' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(9,31): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(14,7): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(14,48): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(14,68): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(14,89): error TS2339: Property 'transactions' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(15,7): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(15,28): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(16,7): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(16,28): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(17,7): error TS2339: Property 'transactions' does not exist on type 'RouterContext<any, {}>'.
src/routes/mine.ts(19,18): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/status.ts(4,18): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(13,25): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(22,43): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/transaction.ts(22,55): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(29,7): error TS2339: Property 'logging' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(45,29): error TS2551: Property 'dbPath' does not exist on type 'RouterContext<any, {}>'. Did you mean 'path'?
src/routes/transaction.ts(50,7): error TS2339: Property 'logging' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(55,19): error TS2339: Property 'network' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(57,13): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(64,9): error TS2339: Property 'logging' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(66,15): error TS2339: Property 'connection' does not exist on type 'RouterContext<any, {}>'.
src/routes/transaction.ts(78,7): error TS2339: Property 'transactions' does not exist on type 'RouterContext<any, {}>'.

11:18:36 AM - Found 32 errors. Watching for file changes.
```

**Comment by cedriking** [comment]
Hello @kespinola , this has been solved (for the missing txs) on the latest version (1.0.25).

Thanks for reporting!

**Comment by kespinola** [comment]
Awesome @cedriking. Great job on this project. Big help when developing arweave backed applications. I was having lots of trouble with testweave.
