### ISSUE TITLE
error while loading smartweave contract

### ISSUE THREAD

**Issue by ppedziwiatr** [textury/arlocal#70]
Hey,

Since the https://github.com/textury/arlocal/issues/63 has been fixed - I've upgraded both arweave.js and arlocal in our testnet (https://testnet.redstone.tools/) to latest versions (arweave.js to 1.10.23 and arlocal to 1.1.21).

Now - while trying to load contract with smartweave.js (with arweave.js 1.10.23)
```js
const arweave = Arweave.init({
    host: 'testnet.redstone.tools',
    protocol: 'https',
    port: 443,
  });
  const result = await readContract(arweave,"6hzHw8wwOuojRMpFOzlJCWJm2ls1Ch5L1U2gFLQI7NM")
```

I'm getting this error (previously the "offset" error from https://github.com/textury/arlocal/issues/63 was thrown)
```
0|index  | [23.02.2022, 12:36:44]   <-- GET /tx/6hzHw8wwOuojRMpFOzlJCWJm2ls1Ch5L1U2gFLQI7NM/offset
0|index  | [23.02.2022, 12:36:44] {
0|index  |   id: '6hzHw8wwOuojRMpFOzlJCWJm2ls1Ch5L1U2gFLQI7NM',
0|index  |   owner: 'xdEWn5OtEUVfN5tGX7E73wtIGNT2wKf3NZa3bqTEvC8yVhMSRXxmMx555puRfsWY6-SXc5Mv5S4DPa-KiCt9tLBDPizXn8dQ6zI6N5fuRa0hmVHphEDXIOZ5EFxIYqZe3HmrAh5xQJors3SFMBhPcBoCzxOd8Ce8Th78VysMjYnny1q0GfywcxZD87Rao-lrEZQh3pVOw_bkvAoIlaUE9SZKKW3JEWaOIQzFMfk910ngL6frqfIlgMRtQv3VoTpSHTPBVNDEfW-9W7T6nocHtMwLB8NK4ov9u0x2vILVK-_MbD9s3Nrn1L5roGcaUaAA96D1hxfdBPhOjiaXXuMNZeYOPYCkneke0ba7gX_G-8n9rFpylya7twTFoPAj1JSnftrVjBBXd5mt7EM0z76zdNN6yk-4S89Dwoc4ussPxzVLYmFB22WkQHjtEqg1QHq4ASqAmP1LSwywihZGhnycpJH8Ty7zaKUvwlasvA9ZPM3o2pzJG4cmTgJth-Qul-L3cNQ4__T-LOzMdJ9Ey3BraBYLu9GvnWo4T8yJYEKN9CCsrVepCkoGcz2_Y78smLJlQ8o9Or4cBoDeFv1QWUyZgrNBLEzAojGJ28LtzF4pmakKDKAtv9Y7XzpqY0NttFp8n2U6R-tADL_cp3evy13sE4q_xFavL4_EJKa1VL50chU',
0|index  |   tags: [
0|index  |     { name: 'QXBwLU5hbWU', value: 'U21hcnRXZWF2ZUNvbnRyYWN0' },
0|index  |     { name: 'QXBwLVZlcnNpb24', value: 'MC4zLjA' },
0|index  |     {
0|index  |       name: 'Q29udHJhY3QtU3Jj',
0|index  |       value: 'N01IaGtNVzMzZmd3SVQtSFc2WTJ3WkQwMVN2dzJyT1F6MXYzUmFvMlhKOA'
0|index  |     },
0|index  |     { name: 'U0RL', value: 'UmVkU3RvbmU' },
0|index  |     { name: 'Q29udGVudC1UeXBl', value: 'YXBwbGljYXRpb24vanNvbg' }
0|index  |   ],
0|index  |   target: '',
0|index  |   quantity: '0',
0|index  |   reward: '25546716',
0|index  |   signature: 'qLSjs0kqrcYCmvieM-3bft2g2cgcRD_ER59iwXYx3kvjP0oIoLaSTnx9RPBrDjD13K2lfoCvP8X6FGy8UTSwURJzcCeqihxbot_tMWgYwvNVWYrjI6WbHVbG54L8U-v0JjniG_gKk06y8Skl4We5_SL5ZNxg31fb5jy-lVRS7CMQjztKfPyGt9fKFIYJMNRIZAKsX7uILlUhbhu6MHztWBGuTmPV2Y6I42KUveH4uQNEonsLpd99tEZRNHUf4ODsGQe1vBIKD9lTG-XF98G78YtE5WQyyoT5oWNEUzZp-B3JfJlCkG6EIgptI4JsGLaWUQ2hY9fDilxCQViauLecHSb6GjbqL9i-HN9ryDK2ZKW4P-rh1WNQZcUGymKxhinvbhBCQHuf0uK4mZn0-Ki6nsgSd9Cm8m5Ud2xoxzZHOX254xv94PDrmkyfeSyIHmd42a3YG2Hqzu-L0dNckOwDjb52SdUH-BeSnDEXyoYVkyf6ySxBibxdqKbqAyuk5HCrIs-FDP3nOaDihlBWIwMLOwnU8ZVdnpLTb0J6QKwSm0F609Q_NojLljwCByYig4JqRaOkbNF1gh2lx89FGrn8t6EgoNTnRRGP-AAGYFqw5bSKn0ktWMsh7A2v0SiXKa8YyKGx7sv7hnMQaEg-eCVQHF7QtvUOUreusgbqeOv_JHA',
0|index  |   last_tx: '00034b2405uck4tns5ij6cniiwlv7r7eeci2b3v1vimhxxjnpid05yrzbj13mulc',
0|index  |   data_size: 13,
0|index  |   content_type: 'application/json',
0|index  |   format: 2,
0|index  |   height: 419173,
0|index  |   owner_address: 'rpx3X2kIfWPkbf9CvNVRFJR3OuJDtjXuWaQOQAeJujU',
0|index  |   data_root: 'GCwIrfft_Q4k5xnIWqnfdhEBGhNEbylpXT0N_e40FjM',
0|index  |   parent: null,
0|index  |   block: 'oecjqsw9vwh8fksx5g8e7i90loghwqm9waht3fnl7ke659xg95mno3d5ifywrd16',
0|index  |   created_at: '2022-02-23T08:26:25.188Z'
0|index  | }
0|index  | [23.02.2022, 12:36:44]   <-- GET /mine
0|index  | {
0|index  |   error: TypeError: Cannot read properties of undefined (reading 'findOne')
0|index  |       at /home/ec2-user/redstone-sw-testnet/node_modules/arlocal/bin/routes/transaction.js:106:43
0|index  |       at Generator.next (<anonymous>)
0|index  |       at fulfilled (/home/ec2-user/redstone-sw-testnet/node_modules/arlocal/bin/routes/transaction.js:5:58)
0|index  | }
0|index  | [23.02.2022, 12:36:44]   --> GET /tx/6hzHw8wwOuojRMpFOzlJCWJm2ls1Ch5L1U2gFLQI7NM/offset 404 10ms -
```

It works when I'm reading the contract with the arweave.js 1.10.18.

**Comment by fuadop** [comment]
can you retest now @ppedziwiatr ?

**Comment by ppedziwiatr** [comment]
It works! Thanks for the quick fix! 🙏
